$:.unshift File.dirname(__FILE__)
require 'jmeter_runner'

API_LOAD_TEST_HOME = File.dirname(File.absolute_path(__FILE__))
CONFIG_HOME = API_LOAD_TEST_HOME.split('/')[0..-2].join('/')
IGNORED_JMX_FILES = ["oauth.jmx"]
UPDATE_JMX_FILES = ["update-attendance.jmx", "update-gradebooks.jmx"]

desc "Clean Result directory"
task :clean do
  if Dir.exists? "#{API_LOAD_TEST_HOME}/result"
    FileUtils.remove_dir("#{API_LOAD_TEST_HOME}/result")
  end
end

desc "Run one thread per JMX file and check for errors"
task :verifyJmxFileLocal => [:checkJmeterHome, :checkServerProcesses] do
  current_dir = File.dirname(__FILE__)
  test_dir = "#{API_LOAD_TEST_HOME}/test"
  if Dir.exists? test_dir
    FileUtils.remove_dir(test_dir)
  end
  runner = ApiLoadTest::Runner.new(
      {
          :jmeter_exec => @jmeter_exec,
          :max_threads => 0,
          :result_dir => test_dir,
          :jmeter_prop => "#{CONFIG_HOME}/local.properties",
          :ignore => IGNORED_JMX_FILES
      }
  )
  runner.collect_all_data(CONFIG_HOME, [1])
  errors = runner.collect_all_errors(CONFIG_HOME)
  contains_error = false
  errors.each do |scenario, scenario_errors|
    unless scenario_errors.empty?
      puts "Scenario = #{scenario}:\t Error Count = #{scenario_errors.size}"
      contains_error = true
    end
  end
  if contains_error
    raise "Error exists!"
  else
    puts "No error found"
  end
end

desc "Run Load Tests"
task :runLoadTests => [:checkJmeterHome] do
  result_dir = "#{API_LOAD_TEST_HOME}/load_test_result/single_node"
  runner = ApiLoadTest::Runner.new(
      {
          :jmeter_exec => @jmeter_exec,
          :jmeter_prop => "#{CONFIG_HOME}/local.properties",
          :result_dir => result_dir,
          :max_avg_elapsed_time => 300000,
          :ignore => IGNORED_JMX_FILES
      }
  )
  runner.collect_all_data(CONFIG_HOME, (0..20).collect{|x| 2**x})
  File.open("#{result_dir}/result.json", "w") do |f|
    f.write(runner.aggregate_all_result().to_json)
  end
end

desc "Run Read-Only Odin 150k Load Tests on SLIRP"
task :runReadOnlyOdin150kLoadTestsOnSlirp => [:checkJmeterHome] do
  result_dir = "#{API_LOAD_TEST_HOME}/load_test_result/single_node"
  runner = ApiLoadTest::Runner.new(
      {
          :jmeter_exec => @jmeter_exec,
          :jmeter_prop => "#{CONFIG_HOME}/odin-slirp/slirp.properties",
          :result_dir => result_dir,
          :max_avg_elapsed_time => 300000,
          :ignore => [IGNORED_JMX_FILES, UPDATE_JMX_FILES].flatten!
      }
  )
  runner.collect_all_data(CONFIG_HOME, (0..1).collect{|x| 2**x})
  File.open("#{result_dir}/result.json", "w") do |f|
    f.write(runner.aggregate_all_result().to_json)
  end
end

desc "Run Read-Only Odin 150k Multiple Jmeter Nodes Load Tests on SLIRP"
task :runReadOnlyMultiNodeOdin150kLoadTestsOnSlirp => [:checkJmeterHome] do
  result_dir = "#{API_LOAD_TEST_HOME}/load_test_result/multi_node"
  runner = ApiLoadTest::Runner.new(
      {
          :jmeter_exec => @jmeter_exec,
          :jmeter_prop => "#{CONFIG_HOME}/odin-slirp/slirp.properties",
          :result_dir => result_dir,
          :remote => true,
          :remote_servers => ["parmongo02.slidev.org", "parmongo03.slidev.org"],
          :ignore => IGNORED_JMX_FILES
      }
  )
  runner.collect_all_data(CONFIG_HOME, (0..4).collect{|x| 2**x})
  File.open("#{result_dir}/result.json", "w") do |f|
    f.write(runner.aggregate_all_result().to_json)
  end
end

desc "Run Multiple Jmeter Nodes Load Tests"
task :runMultiNodesTests => [:checkJmeterHome] do
  result_dir = "#{API_LOAD_TEST_HOME}/result/result-4jmeter-1api-60timeout"
  runner = ApiLoadTest::Runner.new(
      {
          :jmeter_exec => @jmeter_exec,
          :jmeter_prop => "#{CONFIG_HOME}/local.properties",
          :result_dir => result_dir,
          :remote => true,
          :remote_servers => ["parmongo01.slidev.org"],
          :ignore => IGNORED_JMX_FILES
      }
  )
  runner.collect_all_data(CONFIG_HOME, (0..20).collect{|x| 2**x})
  File.open("#{result_dir}/result.json", "w") do |f|
    f.write(runner.aggregate_all_result().to_json)
  end
end

desc "Aggregate Multi Node Test Results"
task :aggregateMultiNodeTestResults do
  result_dir = "#{API_LOAD_TEST_HOME}/multinode"
  runner = ApiLoadTest::Runner.new({:result_dir => result_dir})
  File.open("#{result_dir}/result.json", "w") do |f|
    f.write(runner.aggregate_multinode_test_result().to_json)
  end
end

task :checkServerProcesses do
  {   8080 => "API",
      8082 => "SimpleIDP"
  }.each do |port, server|
    processId = `lsof -P -i:#{port} -sTCP:LISTEN -t`
    raise "#{server} should be running" if processId.empty?
  end
end

task :checkJmeterHome do
  if ENV["JMETER_HOME"].nil?
    raise <<END
Please set environment variable JMETER_HOME to your JMeter root. For example,
  export JMETER_HOME="/opt/apache-jmeter"
END
  else
    @jmeter_exec = "#{ENV["JMETER_HOME"]}/bin/jmeter"
  end
end

task :default => :runLoadTests

desc "Test"
task :test do
  get_jmx_files
end

private

def get_jmx_files
  file_to_scenario = {}
  Dir.foreach CONFIG_HOME do |file|
    if match_index = file =~ /[.]jmx$/
      #next if IGNORED_JMX_FILES.include?(file)
      file_to_scenario[File.join(CONFIG_HOME, file)] = file[0..(match_index - 1)]
    end
  end
  p file_to_scenario
end
