source 'http://rubygems.org'

gem 'rails', '3.2.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'json'

gem 'execjs'

gem 'therubyracer'

gem 'rest-client'
gem 'mocha'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
group :deoployment, :production do
	gem 'capistrano'
	gem 'thin'
end

# To use debugger
# gem 'ruby-debug'

# Lets use SimpleCov for Ruby > 1.9
gem 'simplecov', :require=>false, :group=>:test
gem 'simplecov-rcov', :require=>false, :group=>:test
# gem 'rspec', :require=>false, :group=>:test
# gem 'rspec-rails', :require=>false, :group=>:test
# gem 'webrat', :require=>false, :group=>:test

#Cucumber
# gem 'cucumber'
# gem 'cucumber-rails'

#Use Roodi for style check
gem 'roodi', :require=>false

#Use rails_best_practices to check your design
gem 'rails_best_practices', :require=>false

