source 'http://rubygems.org'

gem 'rails', '3.2.12'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

#gem 'sqlite3'

gem 'json'

gem 'execjs'

gem 'therubyracer'

gem 'oauth2'

gem 'activeresource-response'
gem 'kaminari'

# Better than the Rails Logger
gem 'logging-rails', :require => 'logging/rails'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'jquery-datatables-rails'
  gem 'jquery-ui-rails'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
group :deployment, :integration do
	gem 'capistrano'
	gem 'capistrano-ext'
	gem 'thin'
end

# To use debugger
# gem 'ruby-debug'

 # To use debugger
 # gem 'ruby-debug'
#gem 'ruby-debug19', :require => 'ruby-debug'

## Something is wrong here - but we should figure out how to enable ruby debug.  This is what you need to use to debug on a Mac.
#gem 'linecache19', '0.5.13', :path => "~/.rvm/gems/ruby-1.9.3-p#{RUBY_PATCHLEVEL}/gems/linecache19-0.5.13/"
#gem 'ruby-debug-base19', '0.11.26', :path => "~/.rvm/gems/ruby-1.9.3-p#{RUBY_PATCHLEVEL}/gems/ruby-debug-base19-0.11.26/"
#gem 'ruby-debug19', :require => 'ruby-debug'
gem 'ci_reporter'
gem 'test-unit'

# Lets use SimpleCov for Ruby > 1.9
group :development, :test do

	gem 'simplecov', :require=>false, :group=>:test
	gem 'simplecov-rcov', :require=>false, :group=>:test
	# gem 'turn', "~> 0.9.4"
end
