#!/usr/bin/env rake
require "bundler/gem_tasks"
require 'rake/testtask'

Rake::TestTask.new do |t|
   t.libs << "test"
   t.test_files = FileList['test/test*.rb']
   t.verbose = true
end

Rake::TestTask.new do |t|
   t.libs << "test"
   t.name = "integrationTest"
   t.test_files = FileList['test/integration_test.rb']
   t.verbose = true
end

task :default =>  'test'

namespace :test do

  desc 'Measures test coverage'
  task :coverage do
    rm_f "coverage"
    rm_f "coverage.data"
    rcov = "rcov --aggregate coverage.data --text-summary -Ilib"
    system("#{rcov} --html test/test_*.rb")
  end

end

