source 'http://rubygems.org'

gem 'rails', '3.2.3'

#gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'resque'
#gem 'resque-mongo'
gem "resque-scheduler"

#gem 'SystemTimer'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end

# Lets use SimpleCov for Ruby > 1.9
group :development, :test do
  gem 'simplecov', :require=>false, :group=>:test
  gem 'simplecov-rcov', :require=>false, :group=>:test

end