#!/usr/bin/env ruby
require 'fileutils'

OUT_DIR = "writeback_on"
FileUtils.mkdir OUT_DIR 

10.times do |i|
  %x(mongo 02f7abaa9764db2fa3c1ad852247cd4ff06b2c0a pantomcat-setup/unset-favorite-color.js)
  %x(jmeter -n -q pantomcat.properties -t pantomcat01.jmx -l #{OUT_DIR}/out-run#{i}.log)
end
