/*
 * Copyright 2012-2013 inBloom, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.20 at 03:09:04 PM EDT 
//


package org.slc.sli.sample.entities;

import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Academic distinctions earned by or awarded to the student
 * 
 * <p>Java class for AcademicHonor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcademicHonor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AcademicHonorsType" type="{http://ed-fi.org/0100}AcademicHonorsType"/>
 *         &lt;element name="HonorsDescription" type="{http://ed-fi.org/0100}HonorsDescription" minOccurs="0"/>
 *         &lt;element name="HonorAwardDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcademicHonor", propOrder = {
    "academicHonorsType",
    "honorsDescription",
    "honorAwardDate"
})
public class AcademicHonor {

    @XmlElement(name = "AcademicHonorsType", required = true)
    protected AcademicHonorsType academicHonorsType;
    @XmlElement(name = "HonorsDescription")
    protected String honorsDescription;
    @XmlElement(name = "HonorAwardDate", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Calendar honorAwardDate;

    /**
     * Gets the value of the academicHonorsType property.
     * 
     * @return
     *     possible object is
     *     {@link AcademicHonorsType }
     *     
     */
    public AcademicHonorsType getAcademicHonorsType() {
        return academicHonorsType;
    }

    /**
     * Sets the value of the academicHonorsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcademicHonorsType }
     *     
     */
    public void setAcademicHonorsType(AcademicHonorsType value) {
        this.academicHonorsType = value;
    }

    /**
     * Gets the value of the honorsDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHonorsDescription() {
        return honorsDescription;
    }

    /**
     * Sets the value of the honorsDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHonorsDescription(String value) {
        this.honorsDescription = value;
    }

    /**
     * Gets the value of the honorAwardDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getHonorAwardDate() {
        return honorAwardDate;
    }

    /**
     * Sets the value of the honorAwardDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHonorAwardDate(Calendar value) {
        this.honorAwardDate = value;
    }

}
