/*
 * Copyright 2012-2013 inBloom, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.20 at 03:09:04 PM EDT 
//


package org.slc.sli.sample.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This association relates students to their parents, guardians, or caretakers.
 * 
 * <p>Java class for StudentParentAssociation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StudentParentAssociation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StudentReference" type="{http://ed-fi.org/0100}StudentReferenceType"/>
 *         &lt;element name="ParentReference" type="{http://ed-fi.org/0100}ParentReferenceType"/>
 *         &lt;element name="Relation" type="{http://ed-fi.org/0100}RelationType" minOccurs="0"/>
 *         &lt;element name="PrimaryContactStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="LivesWith" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="EmergencyContactStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ContactPriority" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ContactRestrictions" type="{http://ed-fi.org/0100}ContactRestrictions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudentParentAssociation", propOrder = {
    "studentReference",
    "parentReference",
    "relation",
    "primaryContactStatus",
    "livesWith",
    "emergencyContactStatus",
    "contactPriority",
    "contactRestrictions"
})
public class StudentParentAssociation {

    @XmlElement(name = "StudentReference", required = true)
    protected StudentReferenceType studentReference;
    @XmlElement(name = "ParentReference", required = true)
    protected ParentReferenceType parentReference;
    @XmlElement(name = "Relation")
    protected RelationType relation;
    @XmlElement(name = "PrimaryContactStatus")
    protected Boolean primaryContactStatus;
    @XmlElement(name = "LivesWith")
    protected Boolean livesWith;
    @XmlElement(name = "EmergencyContactStatus")
    protected Boolean emergencyContactStatus;
    @XmlElement(name = "ContactPriority")
    protected Integer contactPriority;
    @XmlElement(name = "ContactRestrictions")
    protected String contactRestrictions;

    /**
     * Gets the value of the studentReference property.
     * 
     * @return
     *     possible object is
     *     {@link StudentReferenceType }
     *     
     */
    public StudentReferenceType getStudentReference() {
        return studentReference;
    }

    /**
     * Sets the value of the studentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentReferenceType }
     *     
     */
    public void setStudentReference(StudentReferenceType value) {
        this.studentReference = value;
    }

    /**
     * Gets the value of the parentReference property.
     * 
     * @return
     *     possible object is
     *     {@link ParentReferenceType }
     *     
     */
    public ParentReferenceType getParentReference() {
        return parentReference;
    }

    /**
     * Sets the value of the parentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentReferenceType }
     *     
     */
    public void setParentReference(ParentReferenceType value) {
        this.parentReference = value;
    }

    /**
     * Gets the value of the relation property.
     * 
     * @return
     *     possible object is
     *     {@link RelationType }
     *     
     */
    public RelationType getRelation() {
        return relation;
    }

    /**
     * Sets the value of the relation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationType }
     *     
     */
    public void setRelation(RelationType value) {
        this.relation = value;
    }

    /**
     * Gets the value of the primaryContactStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrimaryContactStatus() {
        return primaryContactStatus;
    }

    /**
     * Sets the value of the primaryContactStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrimaryContactStatus(Boolean value) {
        this.primaryContactStatus = value;
    }

    /**
     * Gets the value of the livesWith property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLivesWith() {
        return livesWith;
    }

    /**
     * Sets the value of the livesWith property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLivesWith(Boolean value) {
        this.livesWith = value;
    }

    /**
     * Gets the value of the emergencyContactStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEmergencyContactStatus() {
        return emergencyContactStatus;
    }

    /**
     * Sets the value of the emergencyContactStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEmergencyContactStatus(Boolean value) {
        this.emergencyContactStatus = value;
    }

    /**
     * Gets the value of the contactPriority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getContactPriority() {
        return contactPriority;
    }

    /**
     * Sets the value of the contactPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setContactPriority(Integer value) {
        this.contactPriority = value;
    }

    /**
     * Gets the value of the contactRestrictions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactRestrictions() {
        return contactRestrictions;
    }

    /**
     * Sets the value of the contactRestrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactRestrictions(String value) {
        this.contactRestrictions = value;
    }

}
