source 'http://rubygems.org'
gem 'rake'
gem 'mustache'

gem 'rspec', :group => :test
gem 'factory_girl', :group => :test
gem 'simplecov', :require => false, :group => :test
gem 'equivalent-xml', :group => :test

## Enable this to remote debug on a Mac.
#gem 'linecache19', '0.5.12', :group => :debug
#gem 'ruby-debug-base19', '0.11.25', :group => :debug
#gem 'ruby-debug19', :require => 'ruby-debug', :group => :debug
#gem 'ruby-debug-ide19', :group => :debug

#
# Enable perftools.rb during profiling.
# gem 'perftools.rb', :group => :test
#

gem 'nokogiri'
