source 'http://rubygems.org'
gem 'rake'
gem 'mustache'
gem 'psych', "1.3.3"

gem 'rspec', :group => :test
gem 'factory_girl', :group => :test
gem 'simplecov', :require => false, :group => :test
gem 'equivalent-xml', :group => :test

#
# Enable perftools.rb during profiling.
# gem 'perftools.rb', :group => :test
#

gem 'nokogiri'
