
###################################################
# Section to setup necessary env vars and overrides
if(ENV['DB_HOST'])
  DB_HOST=ENV['DB_HOST']
else
  DB_HOST = "localhost"
end

if(ENV['MONGO_HOME'])
  MONGO_BIN = ENV['MONGO_HOME']+"/bin/"
else
  MONGO_BIN = ""
end

if(ENV['NO_EXPAND'])
  EXPAND = ""
else
  EXPAND = "--expand"
end
#######################################################

$SUCCESS=true
$failures = Hash.new

#######################################################################################################
# Helper defs

# This method is to run a given test or set of tests that have a dependency on a fixture being loaded
# Inputs: (String) testDirPath = path to a directory of tests or a single feature file (starting in acceptance-tests directory)
# Inputs: (String) collectionName = name of mongo collection to load fixture data to
# Inputs: (String) fixtureFileName = name of json file in the test/data folder
def runFixtureAndTests(testDirPath, collectionName, fixtureFileName)
  setFixture(collectionName,fixtureFileName) {runTests(testDirPath)}
end

# This method is to run a given test of set of test where a fixture is not needed
# Inputs: (String) testDirPath = path to a directory of tests or a single feature file (starting in acceptance-tests directory)
def runTests(testDirPath)
  sh "cucumber #{testDirPath} #{EXPAND} --tags ~@wip -f junit --out . -f pretty" do |success, exit_code|
    if success
      $failures[testDirPath[testDirPath.rindex('/')+1..-1]] = "Passed"
    else
      $failures[testDirPath[testDirPath.rindex('/')+1..-1]] = "Failed"
      $SUCCESS=false
    end
  end
end

def setFixture(collectionName,fixtureFileName,fixtureFilePath="test/data",dropExistingCollection=true)
  #turn true/false into command line option
  dropOption = (dropExistingCollection) ? "--drop":"";
  sh "#{MONGO_BIN}mongoimport #{dropOption} -d sli -c #{collectionName} -h #{DB_HOST} --file #{fixtureFilePath}/#{fixtureFileName}" do |success, exit_code|
    #allow for user to pass block to run the test for each running of setFixture
    if(success && block_given?)
      yield
    else
      puts "Exited with code: #{exit_code.exitstatus}, please confirm that mongo binaries are on your PATH" unless success
    end
  end
end

def addMultipleFixtureFiles(myHash, fixtureFilePath="test/data")
  myHash.each do |key, value|
    setFixture(key,value,fixtureFilePath,false)
  end
end

def setMultipleFixtureFiles(myHash)
  myHash.each do |key, value|
    setFixture(key,value)
  end
end

def displayFailureReport()
  $failures.each do |key, value|
    puts "#{key} tests #{value}"
  end
end

############################################################################################################


######################################################################################################
# Rake tasks

task :default => :production

# This task will be used for end-to-end integration tests but currently just run all
# available acceptance tests
desc "Default Task: Run All Acceptances Tests"
task :production => [:apiTests, :securityTests, :ingestionTests] do
  displayFailureReport()
  if $SUCCESS
    puts "Completed All Tests"
  else
    raise "Tests have failed"
  end
end

# This task is used as an entry point in Jenkins to run API and Security Tests
# It is needed so that it fails the build if there are any failures based on the 
# 'raise' exception logic below.  Rake will exit immediatly if you raise an exception
# before all the tests complete and will show incomplete results
desc "Run API/Security Acceptances Tests"
task :apiAndSecurityTests => [:apiTests, :securityTests] do
  displayFailureReport()
  if $SUCCESS
    puts "Completed All Tests"
  else
    raise "Tests have failed"
  end
end


############################################################
# Ingestion tests start
############################################################
desc "Run Ingestion Acceptances Tests"
task :ingestionTests => [:sampleIngestionTests] do
  displayFailureReport()
end

desc "Run Sample Ingestion Tests"
task :sampleIngestionTests do
  runTests("test/features/ingestion/sample_test")
end

############################################################
# Ingestion tests end
############################################################

############################################################
# API tests start
############################################################
desc "Run API Acceptances Tests"
task :apiTests => [:schoolTests, :studentTests, :teacherTests, :sectionTests, :assessmentTests, :homeUriTests, :associationTests, :validationTests,:listFilterTests, :targetTests, :aggregationTests, :aggregationDiscoveryTests] do
  displayFailureReport()
end

desc "Run Section Tests"
task :sectionTests do
  runFixtureAndTests("test/features/api/entities/section", "section", "section_fixture.json")
end

desc "Run School Tests"
task :schoolTests do
  runFixtureAndTests("test/features/api/entities/school", "school", "school_fixture.json")
end

desc "Run Student Tests"
task :studentTests do
  runFixtureAndTests("test/features/api/entities/student", "student", "student_fixture.json")
end

desc "Run Teacher Tests"
task :teacherTests do
  runFixtureAndTests("test/features/api/entities/teacher", "teacher", "teacher_fixture.json")
end

desc "Run Assessment Tests"
task :assessmentTests do
  runFixtureAndTests("test/features/api/entities/assessment","assessment","assessment_fixture.json")
end

desc "Run Validation Tests"
task :validationTests do
  setFixture("school", "school_fixture.json")
  setFixture("teacher", "teacher_fixture.json")
  runTests("test/features/api/validation")
end

desc "Run List-Filter Tests"
task :listFilterTests do
  Rake::Task["importSandboxData"].execute
  runTests("test/features/api/end_user_stories/lists")
end

desc "Run Target Tests"
task :targetTests do
  Rake::Task["importSandboxData"].execute
  runTests("test/features/api/end_user_stories/targets")
end

# dependecy on importSandboxData so that association tests can depend on the associated
# entiy data to be available
desc "Run Association Tests"
task :associationTests do
  Rake::Task["importSandboxData"].execute
  runTests("test/features/api/associations/student_section_association")
  runTests("test/features/api/associations/student_assessment_association")
  runTests("test/features/api/associations/student_school_association")
  runTests("test/features/api/associations/teacher_school_association")
  runTests("test/features/api/associations/teacher_section_association")
end

desc "Run Home URI Tests"
task :homeUriTests do
  Rake::Task["importSandboxData"].execute
  runTests("test/features/api/home_uri")
end

desc "Run Aggregation Tests"
task :aggregationTests do
  Rake::Task["importSandboxData"].execute
  runTests("test/features/api/end_user_stories/aggregates")
end

desc "Run Aggregation Discovery Tests"
task :aggregationDiscoveryTests do
  runFixtureAndTests("test/features/api/aggregations","aggregation","aggregation_fixture.json")
end
############################################################
# API tests end
############################################################

############################################################
# API Selenium tests start
# NOTE: Do not add these tests to the production run yet!
#       While they can be run locally without issues,
#       Firefox cannot start on Jenkins, and will cause
#       all these tests to fail
############################################################
desc "Run API Selenium Tests"
task :apiSeleniumTests do
  runTests("test/features/apiSelenium")
  displayFailureReport()
  if $SUCCESS
    puts "Completed All Tests"
  else
    raise "Tests have failed"
  end
end
############################################################
# API Selenium tests end
############################################################

############################################################
# Security tests start
############################################################
desc "Run Security Tests"
task :securityTests do
  Rake::Task["importSandboxData"].execute
  runTests("test/features/security")
end
############################################################
# Security tests end
############################################################

############################################################
# Dashboard tests start
############################################################
desc "Run Dashboard Tests"
task :dashboardTests => [:dashboardPopWidgetTests] do
  puts "Completed Dashboard tests"
end

desc "Run Dashboard population widget Tests"
task :dashboardPopWidgetTests do
  runTests("test/features/dashboard/population_widget.feature")
end

desc "Run Dashboard K-3 view Tests"
task :dashboardK3ViewTests do
  runTests("test/features/dashboard/k3view.feature")
end

desc "Run Dashboard YY Tests"
task :dashboardTests do
  runTests("test/features/dashboard")

end
############################################################
# Dashboard tests end
############################################################

desc "Import Sandbox Test Data"
task :importSandboxData do
  testHash = Hash[
    "section" => "section_fixture.json",
    "school" => "school_fixture.json",
    "student" => "student_fixture.json",
    "teacher" => "teacher_fixture.json",
    "staff" => "staff_fixture.json",
    "assessment" => "assessment_fixture.json",
    "studentSchoolAssociation" => "studentSchoolAssociation_fixture.json",
    "teacherSectionAssociation" => "teacherSectionAssociation_fixture.json",
    "studentAssessmentAssociation" => "studentAssessmentAssociation_fixture.json",
    "studentSectionAssociation" => "studentSectionAssociation_fixture.json",
    "teacherSchoolAssociation" => "teacherSchoolAssociation_fixture.json",
    "educationOrganization" => "educationOrganization_fixture.json",
    "educationOrganizationSchoolAssociation" => "school_educationOrganization_fixure.json",
    "aggregationDefinition" => "aggregationdefinition_fixture.json",
    "staffEducationOrganizationAssociation" => "staffEducationOrganizationAssociation_fixture.json",
    "realm" => "realm_fixture.json"
  ]
  setMultipleFixtureFiles(testHash)
  
  smallvilleTestHash = Hash[
    "assessment" => "smallville_assessment_fixture.json",
    "school" => "smallville_schools_fixture.json",
    "sectionAssessmentAssociation" => "smallville_section_assessment_fixture.json",
    "section" => "smallville_sections_fixture.json",
    "studentAssessmentAssociation" => "smallville_student_assessment_fixture.json",
    "studentSchoolAssociation" => "smallville_student_school_association_fixture.json",
    "studentSectionAssociation" => "smallville_student_section_association_fixture.json",
    "student" => "smallville_students_fixture.json",
    "teacherSectionAssociation" => "smallville_teacher_sections_fixture.json",
    "teacher" => "smallville_teachers_fixture.json",
    "educationOrganization" => "smallville_educationOrganization_fixture.json",
    "educationOrganizationSchoolAssociation" => "smallville_school_educationOrganization_fixure.json"
  ]
  addMultipleFixtureFiles(smallvilleTestHash, "test/data/smallville")
end



desc "Help information for this Rakefile"
task :help do
  puts <<-eos
This Rakefile assumes one of two things: an environment variable MONGO_HOME
is set to the home directory of mongo (just before bin) or that the mongo binaries
are on your PATH.

By default, the tests run against the deployed API/application that is running on
localhost:8080 and also assumes a mongo server running on localhost (at default port).

By default, any Scenario Outlines will be expanded in the console output for ease of development,
but at the command line, the env var "NO_EXPAND" may be defined to run without expanding the Scenario
Outline to allow for proper JUnit XML output files for display in Jenkins

To change this behavior use the following syntax to override:

cmd>rake property=value <rake Task>

Example:

cmd>rake DB_HOST=myNewDbHost.domain.name api_server_url=my.API.server.com production

The properties available to override are as follows:

DB_HOST                This property selects which mongo instance to set the fixture to (default: localhost)
api_server_url         This property selects which running instance of the API to run tests against (default: localhost)
admintools_server_url  This property selects which running instance of the Admin Tools to run tests against (default: localhost)
sli_idp_server_url     This property selects which running IDP should be used as the SLI IDP (default http://devdanil.slidev.org:8080/idp)
sea_idp_server_url     This property selects which running IDP should be used as a mock State IDP (default http://devopenam1.slidev.com:8080/idp1)
lea_idp_server_url     This property selects which running IDP should be used as a mock District IDP (default http://devopenam1.slidev.com:8080/idp2)
DEBUG             This property tells the test code to display debug output in the console
NO_EXPAND         This property tells cucumber no to expand Scenario Outlines (for use in jenkins)
eos

end
