<CalendarDateReference>
    <CalendarDateIdentity>
        <CalendarDate>
        ${CalendarDate.Date}
        </CalendarDate>
        <CalendarEvent>
        ${CalendarDate.CalendarEvent}
        </CalendarEvent>
    </CalendarDateIdentity>
</CalendarDateReference>