<GradebookEntryIdentity>
    <GradebookEntryType>${GradebookEntry.GradebookEntryType}</GradebookEntryType>
    <DateAssigned>${GradebookEntry.DateAssigned}</DateAssigned>
    <SectionReference>
        <SectionIdentity>
            <EducationalOrgReference>
                <EducationalOrgIdentity>
                    <StateOrganizationId>${GradebookEntry.SectionReference.SectionIdentity.EducationalOrgReference.EducationalOrgIdentity.StateOrganizationId}</StateOrganizationId>
                </EducationalOrgIdentity>
            </EducationalOrgReference>
            <UniqueSectionCode>${GradebookEntry.SectionReference.SectionIdentity.UniqueSectionCode}</UniqueSectionCode>
        </SectionIdentity>
    </SectionReference>
</GradebookEntryIdentity>
