<GradeIdentity>
    <StudentSectionAssociationReference>
        <StudentSectionAssociationIdentity>
            <StudentReference>
                <StudentIdentity>
                    <StudentUniqueStateId>${Grade.StudentSectionAssociationReference.StudentSectionAssociationIdentity.StudentIdentity.StudentUniqueStateId}</StudentUniqueStateId>
                </StudentIdentity>
            </StudentReference>
            <SectionReference>
                <SectionIdentity>
                    <EducationalOrgReference>
                        <EducationalOrgIdentity>
                            <StateOrganizationId>${Grade.StudentSectionAssociationReference.StudentSectionAssociationIdentity.SectionIdentity.EducationalOrgReference.EducationalOrgIdentity.StateOrganizationId}</StateOrganizationId>
                        </EducationalOrgIdentity>
                    </EducationalOrgReference>
                    <UniqueSectionCode>${Grade.StudentSectionAssociationReference.StudentSectionAssociationIdentity.SectionIdentity.UniqueSectionCode}</UniqueSectionCode>
                </SectionIdentity>
            </SectionReference>
        </StudentSectionAssociationIdentity>
    </StudentSectionAssociationReference>
    <GradingPeriodReference>
        <GradingPeriodIdentity>
            <GradingPeriod>${Grade.GradingPeriodReference.GradingPeriodIdentity.GradingPeriod}</GradingPeriod>
            <SchoolYear>${Grade.GradingPeriodReference.GradingPeriodIdentity.SchoolYear}</SchoolYear>
             <StateOrganizationId>${Grade.GradingPeriodReference.GradingPeriodIdentity.StateOrganizationId}</StateOrganizationId>
        </GradingPeriodIdentity>
    </GradingPeriodReference>
</GradeIdentity>
