<GradebookEntryIdentity>
    <GradebookEntryType>${GradebookEntry.GradebookEntryType}</GradebookEntryType>
    <DateAssigned>${GradebookEntry.DateAssigned}</DateAssigned>
    <SectionReference>
        <SectionIdentity>
            <StateOrganizationId>${GradebookEntry.SectionReference.SectionIdentity.StateOrganizationId}</StateOrganizationId>
            <UniqueSectionCode>${GradebookEntry.SectionReference.SectionIdentity.UniqueSectionCode}</UniqueSectionCode>
        </SectionIdentity>
    </SectionReference>
</GradebookEntryIdentity>
