<GraduationPlanReference>
    <GraduationPlanIdentity>
        <GraduationPlanType>
            ${GraduationPlan.GraduationPlanType}
        </GraduationPlanType>
        <TotalCreditsRequired>
            <Credit>
                ${GraduationPlan.TotalCreditsRequired.Credit}
            <Credit>
        </TotalCreditsRequired>
    </GraduationPlanIdentity>
</GraduationPlanReference>