<GradeIdentity>
    <StudentSectionAssociationReference>
        <StudentSectionAssociationIdentity>
            <StudentReference>
                <StudentIdentity>
                    <StudentUniqueStateId>${Grade.GradeIdentity.StudentSectionAssociationReference.StudentSectionAssociationIdentity.StudentIdentity.StudentUniqueStateId}</StudentUniqueStateId>
                </StudentIdentity>
            </StudentReference>
            <SectionReference>
                <SectionIdentity>
                    <EducationalOrgReference>
                        <EducationalOrgIdentity>
                            <StateOrganizationId>${Grade.GradeIdentity.StudentSectionAssociationReference.StudentSectionAssociationIdentity.SectionIdentity.EducationalOrgReference.EducationalOrgIdentity.StateOrganizationId}</StateOrganizationId>
                        </EducationalOrgIdentity>
                    </EducationalOrgReference>
                    <UniqueSectionCode>${Grade.GradeIdentity.StudentSectionAssociationReference.StudentSectionAssociationIdentity.SectionIdentity.UniqueSectionCode}</UniqueSectionCode>
                </SectionIdentity>
            </SectionReference>
            <BeginDate>${Grade.GradeIdentity.StudentSectionAssociationReference.StudentSectionAssociationIdentity.BeginDate}</BeginDate>
        </StudentSectionAssociationIdentity>
    </StudentSectionAssociationReference>
    <GradingPeriodReference>
        <GradingPeriodIdentity>
            <EducationalOrgReference>
                <EducationalOrgIdentity>
                    <StateOrganizationId>${Grade.GradeIdentity.GradingPeriodReference.GradingPeriodIdentity.StateOrganizationId}</StateOrganizationId>
                </EducationalOrgIdentity>
            </EducationalOrgReference>
            <GradingPeriod>${Grade.GradeIdentity.GradingPeriodReference.GradingPeriodIdentity.GradingPeriod}</GradingPeriod>
            <BeginDate>${Grade.GradeIdentity.GradingPeriodReference.GradingPeriodIdentity.BeginDate}</BeginDate>
        </GradingPeriodIdentity>
    </GradingPeriodReference>
</GradeIdentity>
