<ReportCardIdentity>
    <StudentReference>
        <StudentIdentity>
            <StudentUniqueStateId>${ReportCard.StudentReference.StudentIdentity.StudentUniqueStateId}</StudentUniqueStateId>
        </StudentIdentity>
    </StudentReference>
    <GradingPeriodReference>
        <GradingPeriodIdentity>
            <GradingPeriod>${ReportCard.GradingPeriodReference.GradingPeriodIdentity.GradingPeriod}</GradingPeriod>
            <SchoolYear>${ReportCard.GradingPeriodReference.GradingPeriodIdentity.SchoolYear}</SchoolYear>
            <StateOrganizationId>${ReportCard.GradingPeriodReference.GradingPeriodIdentity.StateOrganizationId}</StateOrganizationId>
        </GradingPeriodIdentity>
    </GradingPeriodReference>
</ReportCardIdentity>