<StudentAcademicRecordIdentity>
    <StudentReference>
        <StudentIdentity>
            <StudentUniqueStateId>${StudentAcademicRecord.StudentReference.StudentIdentity.StudentUniqueStateId}</StudentUniqueStateId>
        </StudentIdentity>
    </StudentReference>
    <SessionReference>
        <SessionIdentity>
            <SessionName>${StudentAcademicRecord.SessionReference.SessionIdentity.SessionName}</SessionName>
        </SessionIdentity>
    </SessionReference>
</StudentAcademicRecordIdentity>
