<StudentAcademicRecordReference>
    <StudentReference>
        <StudentIdentity>
            <StudentUniqueStateId>
                ${StudentAcademicRecord.StudentReference.StudentIdentity.StudentUniqueStateId}
            </StudentUniqueStateId>
        </StudentIdentity>
    </StudentReference>
</StudentAcademicRecordReference>
