//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.18 at 04:15:23 PM EST 
//


package org.ed_fi._0100;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import com.sun.xml.bind.Locatable;
import com.sun.xml.bind.annotation.XmlLocation;
import org.xml.sax.Locator;


/**
 * Encapsulates the possible attributes that can be used to lookup the identity of the Learning Objectives.
 * 
 * <p>Java class for LearningObjectiveIdentityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LearningObjectiveIdentityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="LearningObjectiveId" type="{http://ed-fi.org/0100}LearningStandardId"/>
 *         &lt;element name="Objective" type="{http://ed-fi.org/0100}Objective"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LearningObjectiveIdentityType", propOrder = {
    "learningObjectiveIdOrObjective"
})
public class LearningObjectiveIdentityType
    implements Locatable
{

    @XmlElements({
        @XmlElement(name = "Objective", type = String.class),
        @XmlElement(name = "LearningObjectiveId", type = LearningStandardId.class)
    })
    protected List<Object> learningObjectiveIdOrObjective;
    @XmlLocation
    @XmlTransient
    protected Locator locator;

    /**
     * Gets the value of the learningObjectiveIdOrObjective property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the learningObjectiveIdOrObjective property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLearningObjectiveIdOrObjective().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link LearningStandardId }
     * 
     * 
     */
    public List<Object> getLearningObjectiveIdOrObjective() {
        if (learningObjectiveIdOrObjective == null) {
            learningObjectiveIdOrObjective = new ArrayList<Object>();
        }
        return this.learningObjectiveIdOrObjective;
    }

    public Locator sourceLocation() {
        return locator;
    }

    public void setSourceLocation(Locator newLocator) {
        locator = newLocator;
    }

}
