source 'https://rubygems.org'

gem 'rails', '3.2.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'json'
gem 'sqlite3'

gem 'approval', :path => '../admin-tools/approval'
gem 'net-ldap'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'execjs'
gem 'therubyracer'

gem 'rest-client'

group :test do
	gem 'simplecov'
	gem 'simplecov-rcov'
	gem "mocha"
end


# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

group :deployment, :integration do
  # Deploy with Capistrano
  gem 'capistrano'
  # Multi-stage deployment
  gem 'capistrano-ext'
  gem 'thin'
end


# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
