source 'http://rubygems.org'

gem 'rails', '3.1.3'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'execjs'

gem 'therubyracer'

gem 'oauth2'

gem "net-ldap"

gem 'approval', :path => '../approval'

gem 'json'

gem 'rest-client'

group :deployment, :integration do
  # Deploy with Capistrano
  gem 'capistrano'
  # Multi-stage deployment
  gem 'capistrano-ext'
  gem 'thin'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

gem 'jquery-rails'

# Lets use SimpleCov for Ruby > 1.9
group :test do
	gem 'simplecov'
	gem 'simplecov-rcov'
	gem "mocha" ,:require => false
end





