source 'http://rubygems.org'

gem 'rails', '3.2.13'

gem 'execjs'
gem 'therubyracer'
gem 'oauth2'
gem 'net-ldap'
gem 'approval', :path => '../approval'
gem 'json'
gem 'rest-client'
gem 'twitter-bootstrap-rails',
    git: 'git@github.com:seyhunak/twitter-bootstrap-rails.git',
    branch: 'bootstrap3'
gem 'less-rails', git: 'git@github.com:metaskills/less-rails.git'
# gem 'less-rails'
gem 'ruby-recaptcha'

group :deployment, :integration do
  gem 'thin'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

gem 'jquery-rails'

group :test do
  gem 'ci_reporter'
  gem 'test-unit'
	gem 'simplecov'
	gem 'simplecov-rcov'
  gem 'mocha' ,'0.14.0', :require => false
end

gem 'encrypted-cookie-store'
gem 'pry'