source 'http://rubygems.org'

gem 'rails', '3.1.3'
gem 'bson_ext', '1.6.1'
gem 'simple_form'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'uuidtools'
gem 'jquery-rails'
gem 'thin'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', '~> 0.8.3', :require => false
end

group :test, :spec, :cucumber do
    gem 'rspec', '~> 2.9.0'
    gem 'rspec-rails', '>= 2.9'
    gem 'cucumber-rails'
    gem 'factory_girl_rails', '>= 3.0'
end

require 'rubygems'
require 'mongo'

source 'http://gemcutter.org'
gem 'mongo_mapper'

