//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.20 at 03:58:29 AM EST 
//


package org.slc.sli.ingestion.jaxb.domain.sli;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexObjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexObjectType")
@XmlSeeAlso({
    GraduationPlan.class,
    PerformanceLevelDescriptor.class,
    StudentObjectiveAssessment.class,
    StudentAssessmentItem.class,
    GradingPeriod.class,
    AssessmentPeriodDescriptor.class,
    ObjectiveAssessment.class,
    CredentialFieldDescriptor.class,
    DisciplineAction.class,
    BehaviorDescriptor.class,
    PostSecondaryEvent.class,
    Diploma.class,
    OpenStaffPosition.class,
    LeaveEvent.class,
    Staff.class,
    EducationOrganization.class
})
public abstract class ComplexObjectType {


}
