//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.20 at 03:58:29 AM EST 
//


package org.slc.sli.ingestion.jaxb.domain.sli;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parentAgencyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="childAgencyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="feederSchool" type="{}feederSchoolType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parentAgencyId",
    "childAgencyId",
    "feederSchool"
})
@XmlRootElement(name = "educationOrgAssociation")
public class EducationOrgAssociation {

    @XmlElement(required = true)
    protected String parentAgencyId;
    @XmlElement(required = true)
    protected String childAgencyId;
    protected FeederSchoolType feederSchool;

    /**
     * Gets the value of the parentAgencyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentAgencyId() {
        return parentAgencyId;
    }

    /**
     * Sets the value of the parentAgencyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentAgencyId(String value) {
        this.parentAgencyId = value;
    }

    /**
     * Gets the value of the childAgencyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildAgencyId() {
        return childAgencyId;
    }

    /**
     * Sets the value of the childAgencyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildAgencyId(String value) {
        this.childAgencyId = value;
    }

    /**
     * Gets the value of the feederSchool property.
     * 
     * @return
     *     possible object is
     *     {@link FeederSchoolType }
     *     
     */
    public FeederSchoolType getFeederSchool() {
        return feederSchool;
    }

    /**
     * Sets the value of the feederSchool property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeederSchoolType }
     *     
     */
    public void setFeederSchool(FeederSchoolType value) {
        this.feederSchool = value;
    }

}
