package org.talend.designer.codegen.translators.internet.ftp;

import org.talend.core.model.process.INode;
import org.talend.core.model.metadata.IMetadataTable;
import org.talend.core.model.process.ElementParameterParser;
import org.talend.designer.codegen.config.CodeGeneratorArgument;
import java.util.List;
import java.util.Map;

public class TFTPPutMainJava
{
  protected static String nl;
  public static synchronized TFTPPutMainJava create(String lineSeparator)
  {
    nl = lineSeparator;
    TFTPPutMainJava result = new TFTPPutMainJava();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "";
  protected final String TEXT_2 = NL + "try{";
  protected final String TEXT_3 = NL + "\t\tglobalMap.put(\"";
  protected final String TEXT_4 = "_CURRENT_STATUS\", \"No file transfered.\");" + NL + "   \t\tjava.util.Set<String> keySet";
  protected final String TEXT_5 = " = map";
  protected final String TEXT_6 = ".keySet();" + NL + "      \tfor (String key";
  protected final String TEXT_7 = " : keySet";
  protected final String TEXT_8 = "){" + NL + "\t\t\tif(key";
  protected final String TEXT_9 = " == null || \"\".equals(key";
  protected final String TEXT_10 = ")){" + NL + "\t\t\t\tSystem.err.println(\"file name invalid!\");" + NL + "\t\t\t\tcontinue;" + NL + "\t\t\t}" + NL + "\t\t\tString tempdir";
  protected final String TEXT_11 = " =  localdir";
  protected final String TEXT_12 = ";" + NL + "\t\t\tString filemask";
  protected final String TEXT_13 = " = key";
  protected final String TEXT_14 = "; " + NL + "\t\t\tString dir";
  protected final String TEXT_15 = " = null;\t" + NL + "\t\t\tString mask";
  protected final String TEXT_16 = " = filemask";
  protected final String TEXT_17 = ".replaceAll(\"\\\\\\\\\", \"/\") ;\t" + NL + "\t\t\tint i";
  protected final String TEXT_18 = " = mask";
  protected final String TEXT_19 = ".lastIndexOf('/');" + NL + "  \t\t\tif (i";
  protected final String TEXT_20 = "!=-1){" + NL + "\t\t\t\tdir";
  protected final String TEXT_21 = " = mask";
  protected final String TEXT_22 = ".substring(0, i";
  protected final String TEXT_23 = "); " + NL + "\t\t\t\tmask";
  protected final String TEXT_24 = " = mask";
  protected final String TEXT_25 = ".substring(i";
  protected final String TEXT_26 = "+1);\t " + NL + "    \t\t}" + NL + "    \t\tif (dir";
  protected final String TEXT_27 = "!=null && !\"\".equals(dir";
  protected final String TEXT_28 = ")) tempdir";
  protected final String TEXT_29 = " = tempdir";
  protected final String TEXT_30 = " + \"/\" + dir";
  protected final String TEXT_31 = ";  " + NL + "    \t\tmask";
  protected final String TEXT_32 = " = mask";
  protected final String TEXT_33 = ".replaceAll(\"\\\\.\", \"\\\\\\\\.\").replaceAll(\"\\\\*\", \".*\");" + NL + "    \t\tfinal String finalMask";
  protected final String TEXT_34 = " = mask";
  protected final String TEXT_35 = ";" + NL + "    \t\tjava.io.File[] listings";
  protected final String TEXT_36 = " = null;       " + NL + "        \tjava.io.File file";
  protected final String TEXT_37 = " = new java.io.File(tempdir";
  protected final String TEXT_38 = ");" + NL + "        \tif (file";
  protected final String TEXT_39 = ".isDirectory()) {" + NL + "\t            listings";
  protected final String TEXT_40 = " = file";
  protected final String TEXT_41 = ".listFiles(new java.io.FileFilter() {" + NL + "\t                public boolean accept(java.io.File pathname) {" + NL + "\t                    boolean result = false;" + NL + "\t                    if (pathname != null && pathname.isFile()) {                      " + NL + "\t                            result = java.util.regex.Pattern.compile(finalMask";
  protected final String TEXT_42 = ").matcher(pathname.getName()).find(); " + NL + "\t                    \t}" + NL + "\t                    return result;" + NL + "\t                }" + NL + "\t            });" + NL + "        \t} " + NL + "\t    \tif(listings";
  protected final String TEXT_43 = " != null && listings";
  protected final String TEXT_44 = ".length > 0){" + NL + "\t    \t\tfor (int m";
  protected final String TEXT_45 = " = 0; m";
  protected final String TEXT_46 = " < listings";
  protected final String TEXT_47 = ".length; m";
  protected final String TEXT_48 = "++){ " + NL + "\t     \t\t\tif (listings";
  protected final String TEXT_49 = "[m";
  protected final String TEXT_50 = "].getName().matches(mask";
  protected final String TEXT_51 = ")){     " + NL + "\t      \t\t\t\t" + NL + "\t\t      \t\t\t";
  protected final String TEXT_52 = "    \t\t\t" + NL + "\t\t    \t\t\tint mode";
  protected final String TEXT_53 = " = com.jcraft.jsch.ChannelSftp.OVERWRITE;" + NL + "\t\t\t\t\t\t";
  protected final String TEXT_54 = NL + "\t\t\t\t\t\tint mode";
  protected final String TEXT_55 = " = com.jcraft.jsch.ChannelSftp.APPEND;" + NL + "\t\t\t\t\t\t";
  protected final String TEXT_56 = NL + "\t\t\t\t\t\tint mode";
  protected final String TEXT_57 = " = com.jcraft.jsch.ChannelSftp.RESUME;" + NL + "\t\t\t\t\t\t";
  protected final String TEXT_58 = NL + "\t\t\t\t\t\ttry{" + NL + "\t\t    \t\t\t\tc_";
  protected final String TEXT_59 = ".put(listings";
  protected final String TEXT_60 = "[m";
  protected final String TEXT_61 = "].getAbsolutePath(), ";
  protected final String TEXT_62 = ", monitor";
  protected final String TEXT_63 = ", mode";
  protected final String TEXT_64 = ");" + NL + "\t\t    \t\t\t\t " + NL + "\t\t    \t\t\t\t// add info to list will return" + NL + "\t\t    \t\t\t\tmsg_";
  protected final String TEXT_65 = ".add(\"file: \" + listings";
  protected final String TEXT_66 = "[m";
  protected final String TEXT_67 = "].getAbsolutePath() + \", size: \"" + NL + "\t\t                    \t+ listings";
  protected final String TEXT_68 = "[m";
  protected final String TEXT_69 = "].length() + \" bytes upload successfully\");" + NL + "\t\t                                            " + NL + "\t\t    \t\t\t\tglobalMap.put(\"";
  protected final String TEXT_70 = "_CURRENT_STATUS\", \"File transfer OK.\");" + NL + "\t\t    \t\t\t\tif(c_";
  protected final String TEXT_71 = ".stat(";
  protected final String TEXT_72 = "+\"/\"+listings";
  protected final String TEXT_73 = "[m";
  protected final String TEXT_74 = "].getName()).getAtimeString() != null){" + NL + "\t\t    \t\t\t\t\tglobalMap.put(\"";
  protected final String TEXT_75 = "_CURRENT_FILE_EXISTS\",true);" + NL + "\t\t    \t\t\t\t}" + NL + "\t\t    \t\t\t}catch(com.jcraft.jsch.SftpException e_";
  protected final String TEXT_76 = ") {" + NL + "\t\t                \tglobalMap.put(\"";
  protected final String TEXT_77 = "_CURRENT_STATUS\", \"File transfer fail.\");" + NL + "\t\t                \tif(c_";
  protected final String TEXT_78 = ".stat(";
  protected final String TEXT_79 = "+\"/\"+listings";
  protected final String TEXT_80 = "[m";
  protected final String TEXT_81 = "].getName()).getAtimeString() != null){" + NL + "\t\t                \t\tglobalMap.put(\"";
  protected final String TEXT_82 = "_CURRENT_FILE_EXISTS\",true);" + NL + "\t\t                \t}" + NL + "\t\t            ";
  protected final String TEXT_83 = NL + "           \t\t\t\t\tthrow(e_";
  protected final String TEXT_84 = ");" + NL + "\t\t\t\t\t";
  protected final String TEXT_85 = NL + "\t\t\t\t\t\t\tSystem.err.println(\"File permission denied: \"+";
  protected final String TEXT_86 = "+\"/\"+listings";
  protected final String TEXT_87 = "[m";
  protected final String TEXT_88 = "].getName());" + NL + "\t\t\t\t\t";
  protected final String TEXT_89 = "     " + NL + "\t\t                }catch(Exception e_";
  protected final String TEXT_90 = "){" + NL + "\t\t                   if(!(e_";
  protected final String TEXT_91 = " instanceof com.jcraft.jsch.SftpException)) {" + NL + "\t\t                \t\tmsg_";
  protected final String TEXT_92 = ".add(\"file \" + listings";
  protected final String TEXT_93 = "[m";
  protected final String TEXT_94 = "].getAbsolutePath() + \" not found?\");" + NL + "\t\t                   \t\t" + NL + "\t\t                \t\tglobalMap.put(\"";
  protected final String TEXT_95 = "_CURRENT_FILE_EXISTS\",false);" + NL + "\t\t                \t}" + NL + "\t\t                   \tthrow e_";
  protected final String TEXT_96 = ";" + NL + "\t\t                }" + NL + "\t\t\t\t\t\tnb_file_";
  protected final String TEXT_97 = "++;" + NL + "\t      \t\t\t}" + NL + "\t    \t\t}" + NL + "\t    \t}else{" + NL + "\t    \t\tSystem.err.println(\"No match file exist!\");" + NL + "\t    \t}" + NL + "\t    \t" + NL + "\t    \t//do rename" + NL + "\t    \tif(map";
  protected final String TEXT_98 = ".get(key";
  protected final String TEXT_99 = ") != \"\" && key";
  protected final String TEXT_100 = " != map";
  protected final String TEXT_101 = ".get(key";
  protected final String TEXT_102 = ")){" + NL + "\t\t    \ttry{" + NL + "\t\t   \t\t\tc_";
  protected final String TEXT_103 = ".rename(";
  protected final String TEXT_104 = "+\"/\"+key";
  protected final String TEXT_105 = ", ";
  protected final String TEXT_106 = "+\"/\"+map";
  protected final String TEXT_107 = ".get(key";
  protected final String TEXT_108 = "));" + NL + "\t\t   \t\t\tglobalMap.put(\"";
  protected final String TEXT_109 = "_CURRENT_STATUS\", \"File rename OK.\");" + NL + "\t\t   \t\t}catch(com.jcraft.jsch.SftpException e_";
  protected final String TEXT_110 = "){" + NL + "\t\t   \t\t\tglobalMap.put(\"";
  protected final String TEXT_111 = "_CURRENT_STATUS\", \"File rename fail.\");" + NL + "\t\t   \t\t\tthrow e_";
  protected final String TEXT_112 = ";" + NL + "\t   \t\t\t}" + NL + "   \t\t\t}  " + NL + "\t    }" + NL + NL;
  protected final String TEXT_113 = NL + NL + "\t\tString currentStatus_";
  protected final String TEXT_114 = " = \"No file transfered.\";" + NL + "   \t\tjava.util.Set<String> keySet";
  protected final String TEXT_115 = " = map";
  protected final String TEXT_116 = ".keySet();" + NL + "      \tfor (String key";
  protected final String TEXT_117 = " : keySet";
  protected final String TEXT_118 = "){" + NL + "      \t\tif(key";
  protected final String TEXT_119 = " == null || \"\".equals(key";
  protected final String TEXT_120 = ")){" + NL + "\t\t\t\tSystem.err.println(\"file name invalid!\");" + NL + "\t\t\t\tcontinue;" + NL + "\t\t\t}    " + NL + "\t\t\tString tempdir";
  protected final String TEXT_121 = " =  localdir";
  protected final String TEXT_122 = ";" + NL + "\t\t\tString filemask";
  protected final String TEXT_123 = " = key";
  protected final String TEXT_124 = "; " + NL + "\t\t\tString dir";
  protected final String TEXT_125 = " = null;\t" + NL + "\t\t\tString mask";
  protected final String TEXT_126 = " = filemask";
  protected final String TEXT_127 = ".replaceAll(\"\\\\\\\\\", \"/\") ;\t" + NL + "\t\t\tint i";
  protected final String TEXT_128 = " = mask";
  protected final String TEXT_129 = ".lastIndexOf('/');" + NL + "  \t\t\tif (i";
  protected final String TEXT_130 = "!=-1){" + NL + "\t\t\t\tdir";
  protected final String TEXT_131 = " = mask";
  protected final String TEXT_132 = ".substring(0, i";
  protected final String TEXT_133 = "); " + NL + "\t\t\t\tmask";
  protected final String TEXT_134 = " = mask";
  protected final String TEXT_135 = ".substring(i";
  protected final String TEXT_136 = "+1);\t " + NL + "    \t\t}" + NL + "    \t\tif (dir";
  protected final String TEXT_137 = "!=null && !\"\".equals(dir";
  protected final String TEXT_138 = ")) tempdir";
  protected final String TEXT_139 = " = tempdir";
  protected final String TEXT_140 = " + \"/\" + dir";
  protected final String TEXT_141 = ";  " + NL + "    \t\tmask";
  protected final String TEXT_142 = " = mask";
  protected final String TEXT_143 = ".replaceAll(\"\\\\.\", \"\\\\\\\\.\").replaceAll(\"\\\\*\", \".*\");" + NL + "    \t\tfinal String finalMask";
  protected final String TEXT_144 = " = mask";
  protected final String TEXT_145 = ";" + NL + "    \t\tjava.io.File[] listings";
  protected final String TEXT_146 = " = null;       " + NL + "        \tjava.io.File file";
  protected final String TEXT_147 = " = new java.io.File(tempdir";
  protected final String TEXT_148 = ");" + NL + "        \tif (file";
  protected final String TEXT_149 = ".isDirectory()) {" + NL + "\t            listings";
  protected final String TEXT_150 = " = file";
  protected final String TEXT_151 = ".listFiles(new java.io.FileFilter() {" + NL + "\t                public boolean accept(java.io.File pathname) {" + NL + "\t                    boolean result = false;" + NL + "\t                    if (pathname != null && pathname.isFile()) {                      " + NL + "\t                            result = java.util.regex.Pattern.compile(finalMask";
  protected final String TEXT_152 = ").matcher(pathname.getName()).find(); " + NL + "\t                    \t}" + NL + "\t                    return result;" + NL + "\t                \t}" + NL + "\t            \t});" + NL + "        \t}";
  protected final String TEXT_153 = NL + "\t        java.util.List<String> remoteExistsFiles_";
  protected final String TEXT_154 = " = new java.util.ArrayList<String>();" + NL + "\t        \t" + NL + "\t\t\tcom.enterprisedt.net.ftp.FTPFile[] ftpFiles_";
  protected final String TEXT_155 = " = ftp_";
  protected final String TEXT_156 = ".dirDetails(\".\");" + NL + "\t\t\tfor (com.enterprisedt.net.ftp.FTPFile ftpFile : ftpFiles_";
  protected final String TEXT_157 = ") {" + NL + "\t\t\t\tif (!ftpFile.isDir() && !ftpFile.isLink()) {" + NL + "\t\t\t\t\tif(\"\".equals(map";
  protected final String TEXT_158 = ".get(key";
  protected final String TEXT_159 = "))){" + NL + "\t\t\t\t\t\tif (ftpFile.getName().matches(mask";
  protected final String TEXT_160 = ")) {\t\t " + NL + "\t\t\t\t\t\t\tremoteExistsFiles_";
  protected final String TEXT_161 = ".add(ftpFile.getName());" + NL + "\t\t\t\t\t\t}" + NL + "\t\t\t\t\t}else{" + NL + "\t\t\t\t\t\tif (ftpFile.getName().matches(map";
  protected final String TEXT_162 = ".get(key";
  protected final String TEXT_163 = "))) {\t\t " + NL + "\t\t\t\t\t\t\tremoteExistsFiles_";
  protected final String TEXT_164 = ".add(ftpFile.getName());" + NL + "\t\t\t\t\t\t}" + NL + "\t\t\t\t\t}" + NL + "\t\t\t\t}" + NL + "\t\t\t}" + NL + "\t\t\t" + NL + "\t    \tif(listings";
  protected final String TEXT_165 = " != null && listings";
  protected final String TEXT_166 = ".length > 0){" + NL + "\t    \t\tfor (int m";
  protected final String TEXT_167 = " = 0; m";
  protected final String TEXT_168 = " < listings";
  protected final String TEXT_169 = ".length; m";
  protected final String TEXT_170 = "++){ " + NL + "\t\t     \t\ttry{" + NL + "\t\t      \t\t\tif (listings";
  protected final String TEXT_171 = "[m";
  protected final String TEXT_172 = "].getName().matches(mask";
  protected final String TEXT_173 = ")){   " + NL + "\t\t\t\t\t\t\tjava.io.File file_in_localDir = listings";
  protected final String TEXT_174 = "[m";
  protected final String TEXT_175 = "];" + NL + "\t\t\t\t\t\t\tglobalMap.put(\"";
  protected final String TEXT_176 = "_CURRENT_FILE_EXISTS\", remoteExistsFiles_";
  protected final String TEXT_177 = ".contains(file_in_localDir.getName())); " + NL + "\t\t\t\t\t\t\tString newName_";
  protected final String TEXT_178 = " = (\"\".equals(map";
  protected final String TEXT_179 = ".get(key";
  protected final String TEXT_180 = ")))?file_in_localDir.getName():map";
  protected final String TEXT_181 = ".get(key";
  protected final String TEXT_182 = ");" + NL + "\t\t\t\t\t\t\t";
  protected final String TEXT_183 = NL + "\t\t\t\t\t\t\tftp_";
  protected final String TEXT_184 = ".put(tempdir";
  protected final String TEXT_185 = " + \"/\" + file_in_localDir.getName(),\"\".equals(newName_";
  protected final String TEXT_186 = ")?file_in_localDir.getName():newName_";
  protected final String TEXT_187 = ", true);" + NL + "\t\t\t\t\t\t\t\t \t" + NL + "\t\t\t\t\t\t \t// add uploading status to list which will return back to client." + NL + "\t\t\t\t\t\t \tmsg_";
  protected final String TEXT_188 = ".add(\"file: \" + file_in_localDir.getAbsolutePath() + \", size: \"" + NL + "\t                                        + file_in_localDir.length() + \" bytes upload successfully\");" + NL + "\t\t\t\t\t\t\t\t \t" + NL + "\t\t\t\t\t\t \tcurrentStatus_";
  protected final String TEXT_189 = " = \"File rename OK.\";" + NL + "\t        \t\t\t\tglobalMap.put(\"";
  protected final String TEXT_190 = "_CURRENT_FILE_EXISTS\", remoteExistsFiles_";
  protected final String TEXT_191 = ".contains(file_in_localDir.getName()));" + NL + "\t\t            \t\t\t\t" + NL + "\t\t\t\t\t\t\t";
  protected final String TEXT_192 = NL + "\t\t            \t\tif (!(remoteExistsFiles_";
  protected final String TEXT_193 = ".contains(newName_";
  protected final String TEXT_194 = "))){" + NL + "\t        \t\t\t\t\tftp_";
  protected final String TEXT_195 = ".put(tempdir";
  protected final String TEXT_196 = " + \"/\" + file_in_localDir.getName(),newName_";
  protected final String TEXT_197 = ");" + NL + "\t        \t\t\t\t\t" + NL + "\t        \t\t\t\t\t// add uploading status to list which will return back to client." + NL + "\t\t\t\t\t\t \t\tmsg_";
  protected final String TEXT_198 = ".add(\"file: \" + file_in_localDir.getAbsolutePath() + \", size: \"" + NL + "\t                                        + file_in_localDir.length() + \" bytes upload successfully\"); " + NL + "\t                            " + NL + "\t        \t\t\t\t\tcurrentStatus_";
  protected final String TEXT_199 = " = \"File rename OK.\";" + NL + "\t        \t\t\t\t\tglobalMap.put(\"";
  protected final String TEXT_200 = "_CURRENT_FILE_EXISTS\", remoteExistsFiles_";
  protected final String TEXT_201 = ".contains(newName_";
  protected final String TEXT_202 = "));" + NL + "\t\t            \t\t}" + NL + "\t\t            \t\t";
  protected final String TEXT_203 = NL + "\t        \t\t\t\tftp_";
  protected final String TEXT_204 = ".put(tempdir";
  protected final String TEXT_205 = " + \"/\" + file_in_localDir.getName(),newName_";
  protected final String TEXT_206 = ");" + NL + "\t        \t\t\t\t " + NL + "\t        \t\t\t\t// add uploading status to list which will return back to client." + NL + "\t\t\t\t\t\t \tmsg_";
  protected final String TEXT_207 = ".add(\"file: \" + file_in_localDir.getAbsolutePath() + \", size: \"" + NL + "\t                                        + file_in_localDir.length() + \" bytes upload successfully\"); " + NL + "\t                        " + NL + "\t        \t\t\t\tcurrentStatus_";
  protected final String TEXT_208 = " = \"File rename OK.\";" + NL + "\t\t\t\t\t\t\tglobalMap.put(\"";
  protected final String TEXT_209 = "_CURRENT_FILE_EXISTS\", remoteExistsFiles_";
  protected final String TEXT_210 = ".contains(newName_";
  protected final String TEXT_211 = "));" + NL + "\t\t            \t\t\t\t " + NL + "\t\t            \t\t";
  protected final String TEXT_212 = NL + "\t\t            \t\tif ((remoteExistsFiles_";
  protected final String TEXT_213 = ".contains(newName_";
  protected final String TEXT_214 = "))){" + NL + "\t\t    \t\t\t\t\tcom.enterprisedt.net.ftp.FTPFile ftpfile";
  protected final String TEXT_215 = "=ftp_";
  protected final String TEXT_216 = ".fileDetails(newName_";
  protected final String TEXT_217 = ");" + NL + "\t\t\t\t\t\t\t\tlong ftpSize";
  protected final String TEXT_218 = "=ftpfile";
  protected final String TEXT_219 = ".size();" + NL + "\t\t\t\t\t\t\t\tlong localSize";
  protected final String TEXT_220 = "=file_in_localDir.length();" + NL + "\t\t\t\t\t\t\t\tif(!(ftpSize";
  protected final String TEXT_221 = "==localSize";
  protected final String TEXT_222 = ")){" + NL + "\t        \t\t\t\t\t\tftp_";
  protected final String TEXT_223 = ".put(tempdir";
  protected final String TEXT_224 = " + \"/\" + file_in_localDir.getName(),newName_";
  protected final String TEXT_225 = ");" + NL + "\t        \t\t\t\t\t\t" + NL + "\t        \t\t\t\t\t\t// add uploading status to list which will return back to client." + NL + "\t\t\t\t\t\t \t\t\tmsg_";
  protected final String TEXT_226 = ".add(\"file: \" + file_in_localDir.getAbsolutePath() + \", size: \"" + NL + "\t                                        \t+ file_in_localDir.length() + \" bytes upload successfully\"); " + NL + "\t                                        " + NL + "\t        \t\t\t\t\t\tcurrentStatus_";
  protected final String TEXT_227 = " = \"File rename OK.\";" + NL + "\t        \t\t\t\t\t\tglobalMap.put(\"";
  protected final String TEXT_228 = "_CURRENT_FILE_EXISTS\", remoteExistsFiles_";
  protected final String TEXT_229 = ".contains(newName_";
  protected final String TEXT_230 = "));" + NL + "\t        \t\t\t\t\t}" + NL + "\t\t            \t\t}else{" + NL + "\t        \t\t\t\t\tftp_";
  protected final String TEXT_231 = ".put(tempdir";
  protected final String TEXT_232 = " + \"/\" + file_in_localDir.getName(),newName_";
  protected final String TEXT_233 = ");" + NL + "\t        \t\t\t\t\t" + NL + "\t        \t\t\t\t\t// add uploading status to list which will return back to client." + NL + "\t\t\t\t\t\t \t\tmsg_";
  protected final String TEXT_234 = ".add(\"file: \" + file_in_localDir.getAbsolutePath() + \", size: \"" + NL + "\t                                        + file_in_localDir.length() + \" bytes upload successfully\"); " + NL + "\t                                        " + NL + "\t        \t\t\t\t\tcurrentStatus_";
  protected final String TEXT_235 = " = \"File rename OK.\";" + NL + "\t        \t\t\t\t\tglobalMap.put(\"";
  protected final String TEXT_236 = "_CURRENT_FILE_EXISTS\", remoteExistsFiles_";
  protected final String TEXT_237 = ".contains(file_in_localDir.getName()));" + NL + "\t\t            \t\t}" + NL + "\t\t            \t\t";
  protected final String TEXT_238 = NL + "\t\t            \t\tnb_file_";
  protected final String TEXT_239 = "++;" + NL + "\t\t      \t\t\t}" + NL + "\t\t      \t\t}catch(com.enterprisedt.net.ftp.FTPException e_";
  protected final String TEXT_240 = "){" + NL + "\t\t      \t\t\t\t" + NL + "\t  \t\t\t\t\tmsg_";
  protected final String TEXT_241 = ".add(\"file \" + listings";
  protected final String TEXT_242 = "[m";
  protected final String TEXT_243 = "].getAbsolutePath() + \" not found?\");" + NL + "\t  \t\t\t\t\t" + NL + "\t  \t\t\t\t\tcurrentStatus_";
  protected final String TEXT_244 = " = \"File rename fail.\";" + NL + "\t  \t\t\t\t\tglobalMap.put(\"";
  protected final String TEXT_245 = "_CURRENT_FILE_EXISTS\", remoteExistsFiles_";
  protected final String TEXT_246 = ".contains(listings";
  protected final String TEXT_247 = "[m";
  protected final String TEXT_248 = "].getName()));" + NL + "\t  \t\t\t\t\t" + NL + "\t  \t\t\t\t\tthrow e_";
  protected final String TEXT_249 = ";" + NL + "\t\t      \t\t}" + NL + "\t    \t\t}" + NL + "\t    \t}else{" + NL + "\t    \t\tSystem.err.println(\"No match file exist!\");" + NL + "\t    \t}" + NL + "\t    \t  " + NL + "\t    }" + NL + "    \tglobalMap.put(\"";
  protected final String TEXT_250 = "_CURRENT_STATUS\", currentStatus_";
  protected final String TEXT_251 = ");" + NL + " ";
  protected final String TEXT_252 = NL + " \t}catch(Exception e_";
  protected final String TEXT_253 = "){";
  protected final String TEXT_254 = NL + "            throw(e_";
  protected final String TEXT_255 = ");";
  protected final String TEXT_256 = NL + "\t\t\tSystem.err.print(e_";
  protected final String TEXT_257 = ".getMessage());";
  protected final String TEXT_258 = NL + "\t}";

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    stringBuffer.append(TEXT_1);
    
	CodeGeneratorArgument codeGenArgument = (CodeGeneratorArgument) argument;
	INode node = (INode)codeGenArgument.getArgument();
	String localdir = ElementParameterParser.getValue(node, "__LOCALDIR__");
	String cid = node.getUniqueName();
	String dieOnError = ElementParameterParser.getValue(node, "__DIE_ON_ERROR__");
	String overwrite=ElementParameterParser.getValue(node, "__OVERWRITE__");
	String sftpoverwrite=ElementParameterParser.getValue(node, "__SFTPOVERWRITE__");
	String remotedir = ElementParameterParser.getValue(node, "__REMOTEDIR__");
	boolean append = ("true").equals(ElementParameterParser.getValue(node, "__APPEND__"));
	String connection = ElementParameterParser.getValue(node, "__CONNECTION__");
	String useExistingConn = ElementParameterParser.getValue(node, "__USE_EXISTING_CONNECTION__");
	boolean sftp = false;
	if(("true").equals(useExistingConn)){
		List<? extends INode> nodeList = node.getProcess().getGeneratingNodes();
		for(INode n : nodeList){
			if(n.getUniqueName().equals(connection)){
				sftp = ("true").equals(ElementParameterParser.getValue(n, "__SFTP__"));
			}
		}
	}else{
		sftp = ("true").equals(ElementParameterParser.getValue(node, "__SFTP__"));
	}

    stringBuffer.append(TEXT_2);
    
	if(sftp){

    stringBuffer.append(TEXT_3);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_4);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_5);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_6);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_8);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_9);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_10);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_11);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_12);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_13);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_14);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_15);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_16);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_17);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_18);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_19);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_20);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_21);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_22);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_23);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_24);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_25);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_26);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_27);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_28);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_29);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_30);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_31);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_32);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_33);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_34);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_35);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_36);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_37);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_38);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_39);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_40);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_41);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_42);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_43);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_44);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_45);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_46);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_47);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_48);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_49);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_50);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_51);
    if(("overwrite").equals(sftpoverwrite)){
    stringBuffer.append(TEXT_52);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_53);
    }else if(("append").equals(sftpoverwrite)){
    stringBuffer.append(TEXT_54);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_55);
    }else if(("resume").equals(sftpoverwrite)){
    stringBuffer.append(TEXT_56);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_57);
    }
    stringBuffer.append(TEXT_58);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_59);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_60);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_61);
    stringBuffer.append(remotedir);
    stringBuffer.append(TEXT_62);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_63);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_64);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_65);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_66);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_67);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_68);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_69);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_70);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_71);
    stringBuffer.append(remotedir);
    stringBuffer.append(TEXT_72);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_73);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_74);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_75);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_76);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_77);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_78);
    stringBuffer.append(remotedir);
    stringBuffer.append(TEXT_79);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_80);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_81);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_82);
    
        				if(("true").equals(dieOnError)){
					
    stringBuffer.append(TEXT_83);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_84);
    
						}else{
					
    stringBuffer.append(TEXT_85);
    stringBuffer.append(remotedir);
    stringBuffer.append(TEXT_86);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_87);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_88);
    
						}
					
    stringBuffer.append(TEXT_89);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_90);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_91);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_92);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_93);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_94);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_95);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_96);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_97);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_98);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_99);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_100);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_101);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_102);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_103);
    stringBuffer.append(remotedir );
    stringBuffer.append(TEXT_104);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_105);
    stringBuffer.append(remotedir );
    stringBuffer.append(TEXT_106);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_107);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_108);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_109);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_110);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_111);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_112);
    }else{
    stringBuffer.append(TEXT_113);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_114);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_115);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_116);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_117);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_118);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_119);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_120);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_121);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_122);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_123);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_124);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_125);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_126);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_127);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_128);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_129);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_130);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_131);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_132);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_133);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_134);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_135);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_136);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_137);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_138);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_139);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_140);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_141);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_142);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_143);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_144);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_145);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_146);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_147);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_148);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_149);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_150);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_151);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_152);
    
        // for a French FTP server, the 'exists' method available in the library that not works fine,
        // so add remote files fullname to a list then check whether the list contains or not instead of. 

    stringBuffer.append(TEXT_153);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_154);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_155);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_156);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_157);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_158);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_159);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_160);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_161);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_162);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_163);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_164);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_165);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_166);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_167);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_168);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_169);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_170);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_171);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_172);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_173);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_174);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_175);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_176);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_177);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_178);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_179);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_180);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_181);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_182);
    if(append){
    stringBuffer.append(TEXT_183);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_184);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_185);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_186);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_187);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_188);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_189);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_190);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_191);
    }else if(("never").equals(overwrite)){
    stringBuffer.append(TEXT_192);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_193);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_194);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_195);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_196);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_197);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_198);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_199);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_200);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_201);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_202);
    }else if(("always").equals(overwrite)){
    stringBuffer.append(TEXT_203);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_204);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_205);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_206);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_207);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_208);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_209);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_210);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_211);
    }else if(("size_differ").equals(overwrite)){
    stringBuffer.append(TEXT_212);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_213);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_214);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_215);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_216);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_217);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_218);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_219);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_220);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_221);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_222);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_223);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_224);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_225);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_226);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_227);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_228);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_229);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_230);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_231);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_232);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_233);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_234);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_235);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_236);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_237);
    }
    stringBuffer.append(TEXT_238);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_239);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_240);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_241);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_242);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_243);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_244);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_245);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_246);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_247);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_248);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_249);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_250);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_251);
    }
    stringBuffer.append(TEXT_252);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_253);
    
        if(("true").equals(dieOnError)){

    stringBuffer.append(TEXT_254);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_255);
    
		}else{

    stringBuffer.append(TEXT_256);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_257);
    
		}

    stringBuffer.append(TEXT_258);
    return stringBuffer.toString();
  }
}
