#!/bin/bash
#
# sarje-jobscheduler      Start/Stop sarje-jobscheduler.
#
# chkconfig: - 62 38
# description: Instiki is a ruby wiki.
#
# processname: sarje-jobscheduler

# Using the lsb functions to perform the operations.
. /lib/lsb/init-functions

# Process name ( For display )
NAME=sarje-oplogagent
SARJE_HOME=/opt/sarje

DAEMON_CONFIG="$SARJE_HOME/conf/oplogagent-config.yml"
DAEMON_WRAPPER="$SARJE_HOME/oplogagent-wrapper.rb"

PIDFILE=$SARJE_HOME/run/oplogagent.pid
LOG_FILE=$SARJE_HOME/log/oplogagent.log
RETVAL=0

case $1 in
 start)
    $DAEMON_WRAPPER $DAEMON_CONFIG > $LOG_FILE &
    echo $! > $PIDFILE
  ;;
 stop)
  # Stop the daemon.
  if [ -e $PIDFILE ]; then
    kill -9 `cat $PIDFILE`
    rm -f $PIDFILE
  fi
  ;;
 restart)
  # Restart the daemon.
  $0 stop && sleep 2 && $0 start
  ;;
 status)
  # Check the status of the process.
  if [ -e $PIDFILE ]; then
   status_of_proc -p $PIDFILE $DAEMON_WRAPPER "$NAME process" && exit 0 || exit $?
  else
   log_daemon_msg "$NAME Process is not running"
   log_end_msg 0
  fi
  ;;
 *)
  # For invalid arguments, print the usage message.
  echo "Usage: $0 {start|stop|restart|status}"
  exit 2
  ;;
esac
exit $?
