#!/bin/bash
#
# sarje-oplogagent      Start/Stop sarje-oplogagent.
#
# chkconfig: - 62 38
# description: Instiki is a ruby wiki.
#
# processname: sarje-oplogagent

# Using the lsb functions to perform the operations.
. /lib/lsb/init-functions

# Process name ( For display )
NAME=sarje-oplogagent
SARJE_HOME=/opt/sarje

PROG_NAME="oplogagent_daemon.rb"
DAEMON_CONFIG="$SARJE_HOME/conf/minislirp-oplogagent-1-config.yml"
DAEMON="$SARJE_HOME/$PROG_NAME"

LOG_DIR=$SARJE_HOME/log 
PIDFILE=$LOG_DIR/oplogagent-1.pid 
LOG_FILE=$LOG_DIR/oplogagent-1.log 
RETVAL=0

# make sure the log directory exists
mkdir -p $LOG_DIR

case $1 in
 start)
    $DAEMON $DAEMON_CONFIG > $LOG_FILE & 
    echo $! > $PIDFILE
  ;;
 stop)
  # Stop the daemon.
  if [ -e $PIDFILE ]; then
    kill -9 `cat $PIDFILE`
    rm -f $PIDFILE
  fi
  ;;
 restart)
  # Restart the daemon.
  $0 stop && sleep 2 && $0 start
  ;;
 status)
  # Check the status of the process.
  if [ -e $PIDFILE ]; then
     if [ $(ps aux | grep -e '$PROG_NAME' | grep -v grep | wc -l | tr -s "\n") -eq 0 ]; then 
       log_success_msg "$PROG_NAME Process is running."
     else
       log_failure_msg "$PROG_NAME Process is not running"
     fi
  else
   log_failure_msg "$NAME Process is not running"
  fi
  ;;
 *)
  # For invalid arguments, print the usage message.
  echo "Usage: $0 {start|stop|restart|status}"
  exit 2
  ;;
esac
exit $?
