package org.talend.designer.codegen.translators.business.openbravo;

import org.talend.core.model.process.INode;
import org.talend.core.model.process.ElementParameterParser;
import org.talend.designer.codegen.config.CodeGeneratorArgument;

public class TOpenbravoERPOutputBeginJava
{
  protected static String nl;
  public static synchronized TOpenbravoERPOutputBeginJava create(String lineSeparator)
  {
    nl = lineSeparator;
    TOpenbravoERPOutputBeginJava result = new TOpenbravoERPOutputBeginJava();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "final String ob_url_";
  protected final String TEXT_2 = " = ";
  protected final String TEXT_3 = ";" + NL + "final String login_";
  protected final String TEXT_4 = " = ";
  protected final String TEXT_5 = ";" + NL + "final String pwd_";
  protected final String TEXT_6 = " = ";
  protected final String TEXT_7 = ";" + NL + "final String method_";
  protected final String TEXT_8 = " = \"POST\";" + NL + "final String file_";
  protected final String TEXT_9 = " = ";
  protected final String TEXT_10 = ";" + NL + "java.net.Authenticator.setDefault(new java.net.Authenticator() {" + NL + "\tprotected java.net.PasswordAuthentication getPasswordAuthentication() {" + NL + "\t\treturn new java.net.PasswordAuthentication(login_";
  protected final String TEXT_11 = ", pwd_";
  protected final String TEXT_12 = ".toCharArray());" + NL + "\t}" + NL + "});" + NL + "final java.net.URL url_";
  protected final String TEXT_13 = " = new java.net.URL(ob_url_";
  protected final String TEXT_14 = ");" + NL + "final java.net.HttpURLConnection hc_";
  protected final String TEXT_15 = " = (java.net.HttpURLConnection) url_";
  protected final String TEXT_16 = ".openConnection();" + NL + "hc_";
  protected final String TEXT_17 = ".setRequestMethod(method_";
  protected final String TEXT_18 = ");" + NL + "hc_";
  protected final String TEXT_19 = ".setAllowUserInteraction(false);" + NL + "hc_";
  protected final String TEXT_20 = ".setDefaultUseCaches(false);" + NL + "hc_";
  protected final String TEXT_21 = ".setDoOutput(true);" + NL + "hc_";
  protected final String TEXT_22 = ".setDoInput(true);" + NL + "hc_";
  protected final String TEXT_23 = ".setInstanceFollowRedirects(true);" + NL + "hc_";
  protected final String TEXT_24 = ".setUseCaches(false);" + NL + "hc_";
  protected final String TEXT_25 = ".setRequestProperty(\"Content-Type\", \"text/xml\");" + NL + "byte[] bytes_";
  protected final String TEXT_26 = " = new byte[1024];" + NL + "java.io.InputStream is_";
  protected final String TEXT_27 = " = new java.io.BufferedInputStream(new java.io.FileInputStream(file_";
  protected final String TEXT_28 = "));" + NL + "java.io.OutputStream os_";
  protected final String TEXT_29 = " = hc_";
  protected final String TEXT_30 = ".getOutputStream();" + NL + "int read_";
  protected final String TEXT_31 = " = 0;" + NL + "do{" + NL + "\tread_";
  protected final String TEXT_32 = " = is_";
  protected final String TEXT_33 = ".read(bytes_";
  protected final String TEXT_34 = ");" + NL + "\tif(read_";
  protected final String TEXT_35 = ">0){" + NL + "\t\tos_";
  protected final String TEXT_36 = ".write(bytes_";
  protected final String TEXT_37 = ", 0, read_";
  protected final String TEXT_38 = ");" + NL + "\t}" + NL + "}while(read_";
  protected final String TEXT_39 = " >= 1024);" + NL + "os_";
  protected final String TEXT_40 = ".flush();" + NL + "os_";
  protected final String TEXT_41 = ".close();" + NL + "is_";
  protected final String TEXT_42 = ".close();" + NL + "hc_";
  protected final String TEXT_43 = ".connect();" + NL + "if(hc_";
  protected final String TEXT_44 = ".getResponseCode() == 200){" + NL + "\torg.dom4j.io.SAXReader sr_";
  protected final String TEXT_45 = " = new org.dom4j.io.SAXReader();" + NL + "\tis_";
  protected final String TEXT_46 = " = hc_";
  protected final String TEXT_47 = ".getInputStream();" + NL + "\tif(is_";
  protected final String TEXT_48 = ".available()>0){" + NL + "\t\torg.dom4j.Document doc_";
  protected final String TEXT_49 = " = sr_";
  protected final String TEXT_50 = ".read(is_";
  protected final String TEXT_51 = ");" + NL + "\t\torg.dom4j.io.OutputFormat format_";
  protected final String TEXT_52 = " = org.dom4j.io.OutputFormat.createPrettyPrint();" + NL + "      \tformat_";
  protected final String TEXT_53 = ".setEncoding(\"UTF-8\");" + NL + "      \tformat_";
  protected final String TEXT_54 = ".setTrimText(false);" + NL + "      \tjava.io.StringWriter out_";
  protected final String TEXT_55 = " = new java.io.StringWriter();" + NL + "      \torg.dom4j.io.XMLWriter writer_";
  protected final String TEXT_56 = " = new org.dom4j.io.XMLWriter(out_";
  protected final String TEXT_57 = ", format_";
  protected final String TEXT_58 = ");" + NL + "      \twriter_";
  protected final String TEXT_59 = ".write(doc_";
  protected final String TEXT_60 = ");" + NL + "      \twriter_";
  protected final String TEXT_61 = ".close();" + NL + "       \tString content_";
  protected final String TEXT_62 = " = out_";
  protected final String TEXT_63 = ".toString();" + NL + "       \tSystem.out.println(content_";
  protected final String TEXT_64 = ");" + NL + "\t}" + NL + "}else{" + NL + "\tSystem.out.println(\"HTTP Response Code: \"+hc_";
  protected final String TEXT_65 = ".getResponseCode());" + NL + "}" + NL + "hc_";
  protected final String TEXT_66 = ".disconnect();";
  protected final String TEXT_67 = NL + "int nb_line_";
  protected final String TEXT_68 = " = 0;" + NL + "int nb_line_updated_";
  protected final String TEXT_69 = " = 0;" + NL + "int nb_line_created_";
  protected final String TEXT_70 = " = 0;" + NL + "int nb_line_removed_";
  protected final String TEXT_71 = " = 0;" + NL + "int nb_line_unauthorized_";
  protected final String TEXT_72 = " = 0;" + NL + "int nb_line_failed_";
  protected final String TEXT_73 = " = 0;" + NL + "final String ob_url_";
  protected final String TEXT_74 = " = ";
  protected final String TEXT_75 = ";" + NL + "final String login_";
  protected final String TEXT_76 = " = ";
  protected final String TEXT_77 = ";" + NL + "final String pwd_";
  protected final String TEXT_78 = " = ";
  protected final String TEXT_79 = ";" + NL + "final String entity_";
  protected final String TEXT_80 = " = \"";
  protected final String TEXT_81 = "\";" + NL + "java.net.Authenticator.setDefault(new java.net.Authenticator() {" + NL + "\tprotected java.net.PasswordAuthentication getPasswordAuthentication() {" + NL + "\t\treturn new java.net.PasswordAuthentication(login_";
  protected final String TEXT_82 = ", pwd_";
  protected final String TEXT_83 = ".toCharArray());" + NL + "\t}" + NL + "});" + NL + "String urlString_";
  protected final String TEXT_84 = " = ob_url_";
  protected final String TEXT_85 = ".trim() + \"/\" + entity_";
  protected final String TEXT_86 = ".trim() + \"/\";";
  protected final String TEXT_87 = NL + "final String method_";
  protected final String TEXT_88 = " = \"DELETE\";";
  protected final String TEXT_89 = NL + "StringBuilder sb_";
  protected final String TEXT_90 = " = new StringBuilder(\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\" ?>\\n<ob:Openbravo xmlns:ob=\\\"http://www.openbravo.com\\\" xmlns:xsi=\\\"http://www.w3.org/2001/XMLSchema-instance\\\">\\n\");" + NL + "int xmlHeadLength_";
  protected final String TEXT_91 = " = sb_";
  protected final String TEXT_92 = ".length();" + NL + "final String method_";
  protected final String TEXT_93 = " = \"POST\";" + NL + "//The order will be the same as the one in tOpenbravoERPInput." + NL + "final String[] referenceAttributes_";
  protected final String TEXT_94 = " = {\"id\", \"entity-name\", \"identifier\", \"transient\", \"inactive\"};";

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    
	CodeGeneratorArgument codeGenArgument = (CodeGeneratorArgument) argument;
	INode node = (INode)codeGenArgument.getArgument();
	String cid = node.getUniqueName();
    
	String endpoint = ElementParameterParser.getValue(node, "__ENDPOINT__");
	String entityName = ElementParameterParser.getValue(node, "__ENTITYNAME__");
	//String encoding = ElementParameterParser.getValue(node, "__ENCODING__");

	String username = ElementParameterParser.getValue(node, "__USER__");
	String password = ElementParameterParser.getValue(node, "__PASS__");

	String action = ElementParameterParser.getValue(node, "__ACTION__");
	String usingExistingFile = ElementParameterParser.getValue(node, "__USE_EXISTING_FILE__");
	String fileName = ElementParameterParser.getValue(node, "__FILENAME__");
	if("UPDATE_CREATE".equals(action) && "true".equals(usingExistingFile)){

    stringBuffer.append(TEXT_1);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_2);
    stringBuffer.append(endpoint );
    stringBuffer.append(TEXT_3);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_4);
    stringBuffer.append(username );
    stringBuffer.append(TEXT_5);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_6);
    stringBuffer.append(password );
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_8);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_9);
    stringBuffer.append(fileName );
    stringBuffer.append(TEXT_10);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_11);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_12);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_13);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_14);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_15);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_16);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_17);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_18);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_19);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_20);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_21);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_22);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_23);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_24);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_25);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_26);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_27);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_28);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_29);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_30);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_31);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_32);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_33);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_34);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_35);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_36);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_37);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_38);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_39);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_40);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_41);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_42);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_43);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_44);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_45);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_46);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_47);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_48);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_49);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_50);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_51);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_52);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_53);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_54);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_55);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_56);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_57);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_58);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_59);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_60);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_61);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_62);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_63);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_64);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_65);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_66);
    
	}else{

    stringBuffer.append(TEXT_67);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_68);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_69);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_70);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_71);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_72);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_73);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_74);
    stringBuffer.append(endpoint );
    stringBuffer.append(TEXT_75);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_76);
    stringBuffer.append(username );
    stringBuffer.append(TEXT_77);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_78);
    stringBuffer.append(password );
    stringBuffer.append(TEXT_79);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_80);
    stringBuffer.append(entityName );
    stringBuffer.append(TEXT_81);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_82);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_83);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_84);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_85);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_86);
    
	if(action.equals("REMOVE")){

    stringBuffer.append(TEXT_87);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_88);
    
	}else if(action.equals("UPDATE_CREATE")){//if(action.equals("REMOVE")){

    stringBuffer.append(TEXT_89);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_90);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_91);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_92);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_93);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_94);
    
	}//end
}

    return stringBuffer.toString();
  }
}
