INSERT INTO school (full_name, 
					short_name, 
					state_organization_id,
					school_type,
					web_site, 
					charter_status, 
					title_i_part_a_school_designation,
					magnet_special_program_emphasis_school, 
					administrative_funding_control, 
					operational_status)
VALUES("Plymouth-Canton High School",
		"Canton",
		"BOGUS-MI-ID-PCEP-001",
		"Regular",
		"http://pcep.pccs.k12.mi.us/",
		"Not a Charter School",
		"Not designated as a Title I Part A school",
		"No students participate",
		"Public School",
		"Active");

INSERT INTO school (full_name, 
					short_name, 
					state_organization_id,
					school_type,
					web_site, 
					charter_status, 
					title_i_part_a_school_designation,
					magnet_special_program_emphasis_school, 
					administrative_funding_control, 
					operational_status)
VALUES("Plymouth-Salem High School",
		"Salem",
		"BOGUS-MI-ID-PCEP-002",
		"Regular",
		"http://pcep.pccs.k12.mi.us/",
		"Not a Charter School",
		"Not designated as a Title I Part A school",
		"No students participate",
		"Public School",
		"Active");
