//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.17 at 01:12:00 PM EDT 
//


package org.slc.sli.test.edfi.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * This is the base type from which all entity elements are extended.
 * 
 * <p>Java class for ComplexObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexObjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexObjectType")
@XmlSeeAlso({
    Staff.class,
    LeaveEvent.class,
    OpenStaffPosition.class,
    CredentialFieldDescriptor.class,
    AssessmentPeriodDescriptor.class,
    MeetingTime.class,
    AcademicWeek.class,
    ReportCard.class,
    StudentObjectiveAssessment.class,
    AccountCodeDescriptor.class,
    ClassPeriod.class,
    StudentCompetency.class,
    Student.class,
    Cohort.class,
    BellSchedule.class,
    CompetencyLevelDescriptor.class,
    StudentCompetencyObjective.class,
    GradingPeriod.class,
    Session.class,
    Budget.class,
    DisciplineDescriptor.class,
    Payroll.class,
    LearningStandard.class,
    CourseOffering.class,
    ObjectiveAssessment.class,
    ServiceDescriptor.class,
    Parent.class,
    DisciplineIncident.class,
    GraduationPlan.class,
    Course.class,
    PostSecondaryEvent.class,
    ContractedStaff.class,
    GradebookEntry.class,
    Assessment.class,
    PerformanceLevelDescriptor.class,
    AssessmentItem.class,
    StudentAssessmentItem.class,
    Diploma.class,
    CourseTranscript.class,
    StudentAssessment.class,
    Program.class,
    Actual.class,
    LearningObjective.class,
    AttendanceEvent.class,
    CalendarDate.class,
    BehaviorDescriptor.class,
    RestraintEvent.class,
    Account.class,
    StudentAcademicRecord.class,
    DisciplineAction.class,
    Grade.class,
    AssessmentFamily.class,
    EducationOrganization.class,
    StudentGradebookEntry.class,
    Location.class,
    Section.class
})
public abstract class ComplexObjectType {

    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
