//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.06 at 10:00:50 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ed-fi.org/0100", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.slc.sli.test.edfi.entities;
