/*
 * Copyright 2012 Shared Learning Collaborative, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.05.31 at 09:35:49 AM EDT
//


package org.slc.sli.test.edfi.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Encapsulates the possible attributes that can be used to lookup the grading period.
 *
 * <p>Java class for GradingPeriodIdentityType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GradingPeriodIdentityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EducationalOrgReference" type="{http://ed-fi.org/0100}EducationalOrgReferenceType"/>
 *         &lt;element name="GradingPeriod" type="{http://ed-fi.org/0100}GradingPeriodType"/>
 *         &lt;element name="BeginDate" type="{http://ed-fi.org/0100}BeginDateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SLCGradingPeriodIdentityType", propOrder = {
    "educationalOrgReference",
    "gradingPeriod",
    "beginDate"
})
public class SLCGradingPeriodIdentityType {

    @XmlElement(name = "EducationalOrgReference", required = true)
    protected EducationalOrgReferenceType educationalOrgReference;
    @XmlElement(name = "GradingPeriod", required = true)
    protected GradingPeriodType gradingPeriod;
    @XmlElement(name = "BeginDate", required = true)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected String beginDate;

    /**
     * Gets the value of the gradingPeriod property.
     *
     * @return
     *     possible object is
     *     {@link GradingPeriodType }
     *
     */
    public GradingPeriodType getGradingPeriod() {
        return gradingPeriod;
    }

    /**
     * Sets the value of the gradingPeriod property.
     *
     * @param value
     *     allowed object is
     *     {@link GradingPeriodType }
     *
     */
    public void setGradingPeriod(GradingPeriodType value) {
        this.gradingPeriod = value;
    }

    /**
     * Gets the value of the schoolYear property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBeginDate() {
        return beginDate;
    }

    /**
     * Sets the value of the schoolYear property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBeginDate(String value) {
        this.beginDate = value;
    }

    /**
     * Gets the value of the educationalOrgReference property.
     *
     * @return
     *     possible object is
     *     {@link EducationalOrgReferenceType }
     *
     */
    public EducationalOrgReferenceType getEducationalOrgReference() {
        return educationalOrgReference;
    }

    /**
     * Sets the value of the educationalOrgReference property.
     *
     * @param value
     *     allowed object is
     *     {@link EducationalOrgReferenceType }
     *
     */
    public void setEducationalOrgReference(EducationalOrgReferenceType value) {
        this.educationalOrgReference = value;
    }
}
